name: Continuous testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        # Match requirements.txt and dev-requirements.txt
        key: ${{ runner.os }}-pip-${{ hashFiles('*requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install -r requirements.txt -r dev-requirements.txt
    - name: Lint
      run: |
        flake8
    - name: Unit tests
      if: always()
      env:
        DINING_SECRET_KEY: hi
        DINING_DEBUG: on
      run: |
        python manage.py test
