name: Test Dining App

on: [push, pull_request]

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: 'TESTING'
    strategy:
      matrix:
        python: ["3.7"]
        ubuntu: ["ubuntu-20.04"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          # Match requirements.txt and dev-requirements.txt
          key: ${{ runner.os }}-pip-${{ hashFiles('*requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt -r dev-requirements.txt
      - name: Run Tests
        run: coverage run manage.py test
      - name: Output Coverage
        run: coverage report && coverage xml
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v2 # https://github.com/codecov/codecov-action
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage/coverage.xml
          flags: unittests
